/**
  과일로 만든 아이스크림 고르기
 */

SELECT
    HALF.FLAVOR
FROM FIRST_HALF AS HALF
JOIN ICECREAM_INFO AS INFO ON HALF.FLAVOR = INFO.FLAVOR
WHERE 1=1
    AND HALF.TOTAL_ORDER > 3000
    AND INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY HALF.TOTAL_ORDER DESC;